export const REGISTER_REQUEST_BAR = 'REGISTER_REQUEST_BAR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST_BAR = 'LOGIN_REQUEST_BAR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
