export const TEAMS_REQUESTED = 'TEAMS_REQUESTED';
export const TEAMS_FETCH_SUCCESS = 'TEAMS_FETCH_SUCCESS';
export const TEAMS_FETCH_FAILURE = 'TEAMS_FETCH_FAILURE';

export const TEAM_CREATE_SUCCESS = 'TEAM_CREATE_SUCCESS';
export const TEAM_CREATE_FAILURE = 'TEAM_CREATE_FAILURE';

export const TEAM_FETCH_FAILURE = 'TEAM_FETCH_FAILURE';
export const TEAM_FETCH_SUCCESS = 'TEAM_FETCH_SUCCESS';
